name: Generate new release for Give plugin

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Create plugin root directory
      run: "mkdir give-free-form && mv -t ./give-free-form ./assets ./includes ./plugin-updater *.php"

    - name: Generate new Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'give-free-form'
        directory: '.'
        filename: 'give-free-form.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        tag_prefix: ''
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "give-free-form.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: "dev"
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
